### ISSUE TITLE
BUG: C error

### ISSUE THREAD

**Issue by EwenQuim** [noah-software/django_action#4]
The Action fails with a C error. I don't know the mechanics behind this so I can't help you more. Am I missing something ?

Find the full log [here](https://github.com/EwenQuim/recettes/pull/37/checks?check_run_id=1222500415)

It's a nice idea, it would be wonderful if it works! 😉

**Comment by creyD** [comment]
Hi, sorry for taking so long to answer. I have similar problems with my own repository (this repo was created by me). If you find a fix, you may create a PR, sadly I don't have the time to fix it on my own.

**Comment by creyD** [comment]
Sorry that it took so long, I think I fixed it now, there were some dependencies missing in the alpine container. Can you confirm that it works now?
